Task 05 of python exceptions
